apps/testdatas/urls.py
from django.urls import  path

# from .views import TestCaseView, DisplayTestCaseView,MoreTestCaseView,AllTestCaseSiderView,SiderCaseDisplayView,SiderCaseDetailsView   #导入TestCaseView
from .views import ClickAndBackView,NewAddAndCheckView,SearchAndCheckView   #导入ClickAndBackView
from .views import NewAddAndCheckWithRelevanceView,SearchAndCheckWithRelevanceView
from .views import DeleteAndCheckView,EditAndCheckView
from .views import LoginAndCheckView


urlpatterns = [
    # 登录场景的复制页面的url配置
    path('loginandcheckcopy/<path:loginandcheck_id>/', LoginAndCheckView.as_view(), name="login_and_check_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    #相同参数的路径名一定不能一样。比如copy/<path:testcase_id>/与<path:testcase_id>/不能并列存在
    path('clickandbackcopy/<path:clickandback_id>/', ClickAndBackView.as_view(), name="click_and_back_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    #新增场景的复制页面的url配置
    path('newaddandcheckcopy/<path:newaddandcheck_id>/', NewAddAndCheckView.as_view(), name="new_add_and_check_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    # 新增场景的复制页面的url配置,带关联新增
    path('newaddandcheckcopywithrelevance/<path:newaddandcheck_id>/', NewAddAndCheckWithRelevanceView.as_view(), name="new_add_and_check_with_relevance_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    # 查询场景的复制页面的url配置
    path('searchandcheckcopy/<path:searchandcheck_id>/', SearchAndCheckView.as_view(), name="search_and_check_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    # 查询场景的复制页面的url配置,带关联新增
    path('searchandcheckcopywithrelevance/<path:searchandcheck_id>/', SearchAndCheckWithRelevanceView.as_view(), name="search_and_check_with_relevance_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    # 删除场景的复制页面的url配置
    path('deleteandcheckcopy/<path:deleteandcheck_id>/', DeleteAndCheckView.as_view(), name="delete_and_check_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

    # 修改场景的复制页面的url配置
    path('editandcheckcopy/<path:editandcheck_id>/', EditAndCheckView.as_view(), name="edit_and_check_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定



]

app_name = 'clickandback'

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

wanwenyc/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin
xadmin.autodiscover()  #自动发现
#version模块自动注册需要版本控制的MOdel
from xadmin.plugins import xversion  #版本
xversion.register_models()  #自动注册版本
from django.views.static import serve   #导入django处理静态文件的包serve ,用于处理midia路径下的文件
from .settings import MEDIA_ROOT    #导入Settings中配置的MEDIA_ROOT
from .settings import STATIC_ROOT
from django.conf import settings   #debug_toolbar url配置-1-导入设置


urlpatterns = [
    path('admin/', admin.site.urls),  # 配置上传文件的访问处理函数
    path('', xadmin.site.urls),       # 配置上传文件的访问处理函数

    # 配置处理引用midia路径下文件的路径,调用serve方法,需要传入参数{"document_root":MEDIA_ROOT}
    # 配置上传文件的访问处理函数
    path('media/<path:path>', serve, {"document_root": MEDIA_ROOT}),
    path('static/<path:path>', serve, {"document_root": STATIC_ROOT}),

    # 配置点击返回场景url,namespace指明命名空间，用命名空间做限定
    path('testdatas/', include('testdatas.urls', namespace='testdatas')),

    # 配置接口数据url,namespace指明命名空间，用命名空间做限定
    path('testapidatas/', include('testapidatas.urls', namespace='testapidatas')),

    # 配置批量替换场景url,namespace指明命名空间，用命名空间做限定
    path('testupdatadb/', include('testupdatadb.urls', namespace='testupdatadb')),

    # 配置爬取数据场景url,namespace指明命名空间，用命名空间做限定
    path('spiderdata/', include('spiderdata.urls', namespace='spiderdata')),

    # 配置爬取数据场景url,namespace指明命名空间，用命名空间做限定
    # path('shucaiyidate/', include('shucaiyidate.urls', namespace='shucaiyidate')),
]

#debug_toolbar url配置-2-设置url
if settings.DEBUG:  #判断是否为调试模式
    import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),  # 配置debug_toolbar 的url,其中‘__debug__/’可以为任何未使用的路径名
    # ]+urlpatterns
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls))) #  # 配置debug_toolbar 的url,其中‘__debug__/’可以为任何未使用的路径名

templates/apirequestdata/apiRequestData.html
{% extends 'base.html' %}
{% block title %}
    newaddandcheck
{% endblock %}
{% block action_url %}
    {% url 'testdatas:new_add_and_check_with_relevance_id' newaddandcheck.id %}
{% endblock %}
{% block box_h1_title %}
    添加数据
{% endblock %}
{% block table_data %}
    <table cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <label>测试项目:</label>
            </td>
            <td>
                <input id="test_project" name="test_project" type="text" value="{{ newaddandcheck.test_project }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>测试模块:</label>
            </td>
            <td>
                <input id="test_module" name="test_module" type="text" value="{{ newaddandcheck.test_module }}"/>
            </td>
        </tr>

        <!--<tr>-->
            <!--<td>-->
                <!--<label>测试页面:</label>-->
            <!--</td>-->
            <!--<td>-->
                <!--<input id="test_page" name="test_page" type="text" value="{{ newaddandcheck.test_page }}"/>-->
            <!--</td>-->
        <!--</tr>-->

        <tr>
            <td>
                <label>用例优先级:</label>
            </td>
            <td>
                <input type="radio"  name="case_priority"  value="P0" {% if newaddandcheck.case_priority == 'P0' %}checked="checked"{% endif %}>冒烟用例
                <input type="radio"  name="case_priority"  value="P1" {% if newaddandcheck.case_priority == 'P1' %}checked="checked"{% endif %}>系统的重要功能用例
                <input type="radio"  name="case_priority"  value="P2" {% if newaddandcheck.case_priority == 'P2' %}checked="checked"{% endif %}>系统的一般功能用例
                <input type="radio"  name="case_priority"  value="P3" {% if newaddandcheck.case_priority == 'P3' %}checked="checked"{% endif %}>极低级别的用例
            </td>
        </tr>

        <tr>
            <td>
                <label>测试内容的名称:</label>
            </td>
            <td>
                <input id="test_case_title" name="test_case_title" type="text"
                       value="{{ newaddandcheck.test_case_title }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>是否运行:</label>
            </td>
            <td>
                <input type="radio" id="is_run_case" name="is_run_case"  value="true"  {% if newaddandcheck.is_run_case == 1 %} checked="checked"{% endif %}>运行
                <input type="radio" id="is_run_case" name="is_run_case"  value="false" {% if newaddandcheck.is_run_case == 0 %} checked="checked"{% endif %}>不运行
            </td>
        </tr>

        <tr>
            <td>
                <label>确定按钮查找风格:</label>
            </td>
            <td>
                <input id="confirm_ele_find" name="confirm_ele_find"
                       type="text" value="{{ newaddandcheck.confirm_ele_find }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>确定按钮查找风格的确切值:</label>
            </td>
            <td>
                <input id="confirm_ele_find_value" name="confirm_ele_find_value"
                       type="text" value="{{ newaddandcheck.confirm_ele_find_value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>是否点击取消按钮:</label>
            </td>
            <td>
                <input type="radio" id="is_click_cancel" name="is_click_cancel"  value="true" {% if newaddandcheck.is_click_cancel == 1 %} checked="checked"{% endif %}>点击取消按钮
                <input type="radio" id="is_click_cancel" name="is_click_cancel"  value="false" {% if newaddandcheck.is_click_cancel == 0 %} checked="checked"{% endif %}>点击确定按钮
            </td>
        </tr>

        <tr>
            <td>
                <label>取消按钮查找风格:</label>
            </td>
            <td>
                <input id="cancel_ele_find" name="cancel_ele_find"
                       type="text" value="{{ newaddandcheck.cancel_ele_find }}"/>
            </td>

        </tr>

        <tr>
            <td>
                <label>取消按钮查找风格的确切值:</label>
            </td>
            <td>
                <input id="cancel_ele_find_value" name="cancel_ele_find_value"
                       type="text" value="{{ newaddandcheck.cancel_ele_find_value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>是否添加成功:</label>
            </td>
            <td>
                <input type="radio" id="is_submit_success" name="is_submit_success"  value="true" {% if newaddandcheck.is_submit_success == 1 %} checked="checked"{% endif %}>是
                <input type="radio" id="is_submit_success" name="is_submit_success"  value="false" {% if newaddandcheck.is_submit_success  == 0 %} checked="checked"{% endif %}>否
            </td>
        </tr>

        <tr>
            <td>
                <label>是否单页面:</label>
            </td>
            <td>
                <input type="radio" id="is_signel_page" name="is_signel_page"  value="true"  {% if newaddandcheck.is_signel_page == 1 %} checked="checked"{% endif %}>是
                <input type="radio" id="is_signel_page" name="is_signel_page"  value="false"  {% if newaddandcheck.is_signel_page == 0 %} checked="checked"{% endif %}>否
            </td>
        </tr>

         <tr>
            <td>
                <label>页数层xpath路径值:</label>
            </td>
            <td>
                <input id="page_number_xpath" name="page_number_xpath"
                       type="text" value="{{ newaddandcheck.page_number_xpath }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>结果表格查找风格:</label>
            </td>
            <td>
                <input id="result_table_ele_find" name="result_table_ele_find"
                       type="text" value="{{ newaddandcheck.result_table_ele_find }}"/>
            </td>

        </tr>

        <tr>
            <td>
                <label>结果表格查找风格的确切值:</label>
            </td>
            <td>
                <input id="result_table_ele_find_value" name="result_table_ele_find_value"
                       type="text" value="{{ newaddandcheck.result_table_ele_find_value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>结果表格总列数:</label>
            </td>
            <td>
                <input id="table_colnum_counts" name="table_colnum_counts" type="text" value="{{ newaddandcheck.table_colnum_counts }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>用例循环次数:</label>
            </td>
            <td>
                <input id="case_counts" name="case_counts" type="text" value="{{ newaddandcheck.case_counts }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>依赖的点击场景的用例:</label>
            </td>
            <td>
                <select id="depend_click_case" name="depend_click_case">
                    <option value=""
                            {% if newaddandcheck.depend_click_case_id == None %}
                                selected="selected"
                            {% endif %}>
                            ---请选择
                    </option>
                    {%for cab in clickandback_all%}
                        <option
                                value={{cab.id}}
                                        {% if cab.id == newaddandcheck.depend_click_case_id%}
                                            selected="selected"
                                        {% endif %}>
                            [{{ cab.test_project }}]-[{{ cab.test_module }}]-[{{ cab.test_page }}]_{{cab.test_case_title }}]
                        </option>
                    {%endfor%}

                </select>

            </td>
        </tr>

        <tr>
            <td>
                <label>是否附带复制:</label>
            </td>
            <td>
                <input type="radio" id="is_withRelevance" name="is_withRelevance"  value=1 {% if is_withRelevance == 1 %} checked="checked"{% endif %}>附带
                <input type="radio" id="is_withRelevance" name="is_withRelevance"  value=0 {% if is_withRelevance == 0 %} checked="checked"{% endif %}>不附带
            </td>
        </tr>


    </table>
{% endblock %}
{% block box2_a %}
    <a href='{{ django_server_yuming }}/testdatas/newaddandcheck/'>返回数据列表页</a>
{% endblock %}

templates/apirequestdata/apiRequestDataForm.html
{% extends 'base.html' %}
{% block title %}
    newaddandcheck
{% endblock %}
{% block action_url %}
    {% url 'testdatas:new_add_and_check_with_relevance_id' newaddandcheck.id %}
{% endblock %}
{% block box_h1_title %}
    添加数据
{% endblock %}
{% block table_data %}
    <table cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <label>测试项目:</label>
            </td>
            <td>
                <input id="test_project" name="test_project" type="text" value="{{ newaddandcheckform.test_project.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>测试模块:</label>
            </td>
            <td>
                <input id="test_module" name="test_module" type="text" value="{{ newaddandcheckform.test_module.value }}"/>
            </td>
        </tr>

        <!--<tr>-->
            <!--<td>-->
                <!--<label>测试页面:</label>-->
            <!--</td>-->
            <!--<td>-->
                <!--<input id="test_page" name="test_page" type="text" value="{{ newaddandcheckform.test_page.value }}"/>-->
            <!--</td>-->
        <!--</tr>-->

        <tr>
            <td>
                <label>用例优先级:</label>
            </td>
            <td>
                <input type="radio" name="case_priority" value="P0" {% if newaddandcheckform.case_priority.value == 'P0' %} checked="checked"{% endif %}>冒烟用例
                <input type="radio" name="case_priority" value="P1" {% if newaddandcheckform.case_priority.value == 'P1' %} checked="checked"{% endif %}>系统的重要功能用例
                <input type="radio" name="case_priority" value="P2" {% if newaddandcheckform.case_priority.value == 'P2' %} checked="checked"{% endif %}>系统的一般功能用例
                <input type="radio" name="case_priority" value="P3" {% if newaddandcheckform.case_priority.value == 'P3' %} checked="checked"{% endif %}>极低级别的用例
            </td>
        </tr>

        <tr>
            <td>
                <label>测试内容的名称:</label>
            </td>
            <td>
                <input id="test_case_title" name="test_case_title" type="text"
                       value="{{ newaddandcheckform.test_case_title.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>是否运行:</label>
            </td>
            <td>
                <input type="radio" id="is_run_case" name="is_run_case"  value="true" {% if newaddandcheckform.is_run_case.value == 1 %} checked="checked"{% endif %}>运行
                <input type="radio" id="is_run_case" name="is_run_case"  value="false" {% if newaddandcheckform.is_run_case.value  == 0 %} checked="checked"{% endif %}>不运行
            </td>
        </tr>

        <tr>
            <td>
                <label>确定按钮查找风格:</label>
            </td>
            <td>
                <input id="confirm_ele_find" name="confirm_ele_find"
                       type="text" value="{{ newaddandcheckform.confirm_ele_find.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>确定按钮查找风格的确切值:</label>
            </td>
            <td>
                <input id="confirm_ele_find_value" name="confirm_ele_find_value"
                       type="text" value="{{ newaddandcheckform.confirm_ele_find_value.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>是否点击取消按钮:</label>
            </td>
            <td>
                <input type="radio" id="is_click_cancel" name="is_click_cancel"  value="true" {% if newaddandcheckform.is_click_cancel.value == 1 %} checked="checked"{% endif %}>点击取消按钮
                <input type="radio" id="is_click_cancel" name="is_click_cancel"  value="false" {% if newaddandcheckform.is_click_cancel.value == 0 %} checked="checked"{% endif %}>点击确定按钮
            </td>
        </tr>

        <tr>
            <td>
                <label>取消按钮查找风格:</label>
            </td>
            <td>
                <input id="cancel_ele_find" name="cancel_ele_find"
                       type="text" value="{{ newaddandcheckform.cancel_ele_find.value }}"/>
            </td>

        </tr>

        <tr>
            <td>
                <label>取消按钮查找风格的确切值:</label>
            </td>
            <td>
                <input id="cancel_ele_find_value" name="cancel_ele_find_value"
                       type="text" value="{{ newaddandcheckform.cancel_ele_find_value.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>是否添加成功:</label>
            </td>
            <td>
                <input type="radio" id="is_submit_success" name="is_submit_success"  value="true" {% if newaddandcheckform.is_submit_success.value == 1 %} checked="checked"{% endif %}>是
                <input type="radio" id="is_submit_success" name="is_submit_success"  value="false" {% if newaddandcheckform.is_submit_success.value == 0 %} checked="checked"{% endif %}>否
            </td>
        </tr>

        <tr>
            <td>
                <label>是否单页面:</label>
            </td>
            <td>
                <input type="radio" id="is_signel_page" name="is_signel_page"  value="true" {% if newaddandcheckform.is_signel_page.value == 1 %} checked="checked"{% endif %}>是
                <input type="radio" id="is_signel_page" name="is_signel_page"  value="false" {% if newaddandcheckform.is_signel_page.value == 0 %} checked="checked"{% endif %}>否
            </td>
        </tr>

         <tr>
            <td>
                <label>页数层xpath路径值:</label>
            </td>
            <td>
                <input id="page_number_xpath" name="page_number_xpath"
                       type="text" value="{{ newaddandcheckform.page_number_xpath.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>结果表格查找风格:</label>
            </td>
            <td>
                <input id="result_table_ele_find" name="result_table_ele_find"
                       type="text" value="{{ newaddandcheckform.result_table_ele_find.value }}"/>
            </td>

        </tr>

        <tr>
            <td>
                <label>结果表格查找风格的确切值:</label>
            </td>
            <td>
                <input id="result_table_ele_find_value" name="result_table_ele_find_value"
                       type="text" value="{{ newaddandcheckform.result_table_ele_find_value.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>结果表格总列数:</label>
            </td>
            <td>
                <input id="table_colnum_counts" name="table_colnum_counts" type="text" value="{{ newaddandcheckform.table_colnum_counts.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>用例循环次数:</label>
            </td>
            <td>
                <input id="case_counts" name="case_counts" type="text" value="{{ newaddandcheckform.case_counts.value }}"/>
            </td>
        </tr>

        <tr>
            <td>
                <label>依赖的点击场景的用例:</label>
            </td>
            <td>
                <select id="depend_click_case" name="depend_click_case">
                    <option value=""
                            {% if newaddandcheckform.depend_click_case_id.value == None %}
                                selected="selected"
                            {% endif %}>
                             ---请选择
                    </option>
                    {%for cab in clickandback_all%}
                        <option
                                value={{cab.id}}
                                        {% if cab.id == newaddandcheckform.depend_click_case_id.value%}
                                            selected="selected"
                                        {% endif %}>
                            [{{ cab.test_project }}]-[{{ cab.test_module }}]-[{{ cab.test_page }}]_{{cab.test_case_title }}]
                        </option>
                    {%endfor%}

                </select>

            </td>
        </tr>

        <tr>
            <td>
                <label>是否附带复制:</label>
            </td>
            <td>
                <input type="radio" id="is_withRelevance" name="is_withRelevance"  value=1  {% if is_withRelevance == 1 %} checked="checked"{% endif %}>附带
                <input type="radio" id="is_withRelevance" name="is_withRelevance"  value=0  {% if is_withRelevance == 0 %} checked="checked"{% endif %}>不附带
            </td>
        </tr>

    </table>
{% endblock %}
{% block box2_a %}
    <a href='{{ django_server_yuming }}/testdatas/newaddandcheck/'>返回数据列表页</a>
{% endblock %}