apps/spiderdata/urls.py
from django.urls import  path

from .views import SpiderHMChapterImageView  #导入ClickAndBackView



urlpatterns = [
    # 漫画图片页面的url配置
    path('spiderhmchapterdata/<path:spiderhmchapterdata_id>/', SpiderHMChapterImageView.as_view(), name="spider_hm_chapter_data_id"),
    # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定


]

app_name = 'spiderhanman'

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

wanwenyc/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin
xadmin.autodiscover()  #自动发现
#version模块自动注册需要版本控制的MOdel
from xadmin.plugins import xversion  #版本
xversion.register_models()  #自动注册版本
from django.views.static import serve   #导入django处理静态文件的包serve ,用于处理midia路径下的文件
from .settings import MEDIA_ROOT    #导入Settings中配置的MEDIA_ROOT
from .settings import STATIC_ROOT
from django.conf import settings   #debug_toolbar url配置-1-导入设置


urlpatterns = [
    path('admin/', admin.site.urls),  # 配置上传文件的访问处理函数
    path('', xadmin.site.urls),       # 配置上传文件的访问处理函数

    # 配置处理引用midia路径下文件的路径,调用serve方法,需要传入参数{"document_root":MEDIA_ROOT}
    # 配置上传文件的访问处理函数
    path('media/<path:path>', serve, {"document_root": MEDIA_ROOT}),
    path('static/<path:path>', serve, {"document_root": STATIC_ROOT}),

    # 配置点击返回场景url,namespace指明命名空间，用命名空间做限定
    path('testdatas/', include('testdatas.urls', namespace='testdatas')),

    # 配置接口数据url,namespace指明命名空间，用命名空间做限定
    path('testapidatas/', include('testapidatas.urls', namespace='testapidatas')),

    # 配置批量替换场景url,namespace指明命名空间，用命名空间做限定
    path('testupdatadb/', include('testupdatadb.urls', namespace='testupdatadb')),

    # 配置爬取数据场景url,namespace指明命名空间，用命名空间做限定
    path('spiderdata/', include('spiderdata.urls', namespace='spiderdata')),

    # 配置爬取数据场景url,namespace指明命名空间，用命名空间做限定
    # path('shucaiyidate/', include('shucaiyidate.urls', namespace='shucaiyidate')),
]

#debug_toolbar url配置-2-设置url
if settings.DEBUG:  #判断是否为调试模式
    import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),  # 配置debug_toolbar 的url,其中‘__debug__/’可以为任何未使用的路径名
    # ]+urlpatterns
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls))) #  # 配置debug_toolbar 的url,其中‘__debug__/’可以为任何未使用的路径名

templates/spiderhmchapterimage/SpiderHMChapterImage.html
{% extends 'base.html' %}
{% block title %}
    spiderhmchapterimage
{% endblock %}
{% block action_url %}
    {% url 'spiderdata:spider_hm_chapter_data_id' spiderhmchapterdata.id %}
{% endblock %}
{% block box_h1_title %}
    章节漫画展示
{% endblock %}
{% block table_data %}
    <table cellpadding="0" cellspacing="0">
        {% for spiderhmchapterimage_one in spiderhmchapterimage_list %}
            <tr>
                <td>
                    <img src="{{ django_server_yuming }}/media/{{ spiderhmchapterimage_one.content_img }}"></img>
                </td>
            <tr>
        {% endfor %}


{#        <tr>#}
{#            <td>#}
{#                <label>测试项目:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="test_project" name="test_project" type="text" value="{{ loginandcheck.test_project }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>测试模块:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="test_module" name="test_module" type="text" value="{{ loginandcheck.test_module }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>测试页面:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="test_page" name="test_page" type="text" value="{{ loginandcheck.test_page }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>用例优先级:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input type="radio"  name="case_priority"  value="P0" {% if loginandcheck.case_priority == 'P0' %}checked="checked"{% endif %}>冒烟用例#}
{#                <input type="radio"  name="case_priority"  value="P1" {% if loginandcheck.case_priority == 'P1' %}checked="checked"{% endif %}>系统的重要功能用例#}
{#                <input type="radio"  name="case_priority"  value="P2" {% if loginandcheck.case_priority == 'P2' %}checked="checked"{% endif %}>系统的一般功能用例#}
{#                <input type="radio"  name="case_priority"  value="P3" {% if loginandcheck.case_priority == 'P3' %}checked="checked"{% endif %}>极低级别的用例#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>测试内容的名称:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="test_case_title" name="test_case_title" type="text"#}
{#                       value="{{ loginandcheck.test_case_title }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>是否运行:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input type="radio" id="is_run_case" name="is_run_case"  value="true"  {% if loginandcheck.is_run_case == 1 %} checked="checked"{% endif %}>运行#}
{#                <input type="radio" id="is_run_case" name="is_run_case"  value="false" {% if loginandcheck.is_run_case == 0 %} checked="checked"{% endif %}>不运行#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>登录页的url:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="login_url" name="login_url"#}
{#                       type="text" value="{{ loginandcheck.login_url }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>是否自动输入验证码:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input type="radio" id="is_auto_input_code" name="is_auto_input_code"  value="true"  {% if loginandcheck.is_auto_input_code == 1 %} checked="checked"{% endif %}>是#}
{#                <input type="radio" id="is_auto_input_code" name="is_auto_input_code"  value="false" {% if loginandcheck.is_auto_input_code == 0 %} checked="checked"{% endif %}>否#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>验证码xpath路径:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="code_image_xpath" name="code_image_xpath"#}
{#                       type="text" value="{{ loginandcheck.code_image_xpath }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>验证码类型:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="code_type" name="code_type"#}
{#                       type="text" value="{{ loginandcheck.code_type }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>验证码输入框查找风格:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="code_input_ele_find" name="code_input_ele_find"#}
{#                       type="text" value="{{ loginandcheck.code_input_ele_find }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>验证码输入框查找风格的确切值:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="code_input_ele_find_value" name="code_input_ele_find_value"#}
{#                       type="text" value="{{ loginandcheck.code_input_ele_find_value }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>登录按钮查找风格:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="login_button_ele_find" name="login_button_ele_find"#}
{#                       type="text" value="{{ loginandcheck.login_button_ele_find }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>登录按钮查找风格的确切值:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="login_button_ele_find_value" name="login_button_ele_find_value"#}
{#                       type="text" value="{{ loginandcheck.login_button_ele_find_value }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>点击登录按钮后的延时时长（单位秒）:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="click_login_button_delay_time" name="click_login_button_delay_time"#}
{#                       type="text" value="{{ loginandcheck.click_login_button_delay_time }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>用例循环次数:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input id="case_counts" name="case_counts" type="text" value="{{ loginandcheck.case_counts }}"/>#}
{#            </td>#}
{#        </tr>#}
{##}
{##}
{#        <tr>#}
{#            <td>#}
{#                <label>是否附带复制:</label>#}
{#            </td>#}
{#            <td>#}
{#                <input type="radio" id="is_withRelevance" name="is_withRelevance"  value=1 {% if is_withRelevance == 1 %} checked="checked"{% endif %}>附带#}
{#                <input type="radio" id="is_withRelevance" name="is_withRelevance"  value=0 {% if is_withRelevance == 0 %} checked="checked"{% endif %}>不附带#}
{#            </td>#}
{#        </tr>#}


    </table>
{% endblock %}
{% block box2_a %}
    <a href='{{ django_server_yuming }}/spiderdata/spiderhmbook/'>返回数据列表页</a>
{% endblock %}

{% block box2_button %}
    <a href='{% url 'spiderdata:spider_hm_chapter_data_id' nextspiderhmchapterdata.id %}'>下一章</a>
{% endblock %}